#!/usr/bin/env bash
# printing Best School 10 times using while loop
name="Best School"
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "$name"
	fi
	i=$(( i+1 ))
done
