#!/usr/bin/env bash
# printing 1 to 10 with words in it using while loop
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		"4" )
			echo "bad luck from China" ;;
		"9" )
			echo "bad luck from Japan" ;;
		"17" )
			echo "bad luck from Italy" ;;
	esac
	i=$(( i+1 ))
done
